[package]
name = "pixels"
description = "A tiny library providing a GPU-powered pixel frame buffer."
version = "0.0.1"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
repository = "https://github.com/parasyte/pixels"
readme = "README.md"
keywords = ["pixels", "2D", "GPU", "framebuffer"]
categories = ["graphics", "rendering"]
license = "MIT"
include = [
    "/Cargo.*",
    "/LICENSE",
    "/README.md",
    "/img/pixels.png",
    "/shaders/*.spv",
    "/src/**/*",
]

[badges]
travis-ci = { repository = "parasyte/pixels" }
maintenance = { status = "actively-maintained" }

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "012d08d64de924da93289c2b51fb06b22d7348cf" }

[dev-dependencies]
byteorder = "1.3"
env_logger = "0.7"
getrandom = "0.1"
gilrs = "0.7"
log = { version = "0.4", features = ["release_max_level_warn"] }
pixels-mocks = { path = "pixels-mocks" }
simple-invaders = { path = "simple-invaders" }
winit = "0.20.0-alpha4"
winit_input_helper = "0.4.0-alpha4"

[workspace]
members = [
    "pixels-mocks",
    "simple-invaders",
]
