[package]
name = "pixels"
description = "A tiny library providing a GPU-powered pixel frame buffer."
version = "0.0.3"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
repository = "https://github.com/parasyte/pixels"
readme = "README.md"
keywords = ["pixels", "2D", "GPU", "framebuffer"]
categories = ["graphics", "rendering"]
license = "MIT"
include = [
    "/Cargo.*",
    "/LICENSE",
    "/README.md",
    "/img/pixels.png",
    "/shaders/*.spv",
    "/src/**/*",
]

[badges]
travis-ci = { repository = "parasyte/pixels" }
maintenance = { status = "actively-developed" }

[dependencies]
thiserror = "1.0"
wgpu = { version = "0.5" }
# Minimal async executor for running wgpu's futures
pollster = "0.2.0"

# These are only used by the examples, and enabled with features
# See: https://github.com/rust-lang/cargo/issues/1982
beryllium = { version = " 0.1", optional = true }
byteorder = { version = "1.3", optional = true }
env_logger = { version = "0.7", optional = true }
getrandom = { version = "0.1", optional = true }
gilrs = { version = "0.7", optional = true }
line_drawing = { version = "0.8", optional = true }
log = { version = "0.4", features = ["release_max_level_warn"], optional = true }
randomize = { version = "3.0", optional = true }
simple-invaders = { path = "simple-invaders", optional = true }
winit = { version = "=0.20.0-alpha4", optional = true }
winit_input_helper = { version = "=0.4.0-alpha4", optional = true }

[dev-dependencies]
pixels-mocks = { path = "pixels-mocks" }
winit = "=0.20.0-alpha4"

[[example]]
name = "conway"
required-features = ["conway"]

[[example]]
name = "invaders"
required-features = ["invaders"]

[[example]]
name = "minimal-sdl2"
required-features = ["minimal-sdl2"]

[[example]]
name = "minimal-winit"
required-features = ["minimal-winit"]

[features]
default = []
log-deps = ["env_logger", "log"]
random-deps = ["byteorder", "getrandom", "randomize"]
sdl2-deps = ["beryllium"]
winit-deps = ["winit", "winit_input_helper"]

conway = ["line_drawing", "log-deps", "random-deps", "winit-deps"]
invaders = ["gilrs", "log-deps", "random-deps", "simple-invaders", "winit-deps"]
minimal-sdl2 = ["log-deps", "sdl2-deps"]
minimal-winit = ["log-deps", "winit-deps"]

[workspace]
members = [
    "pixels-mocks",
    "simple-invaders",
]

[profile.dev]
debug = false

[patch.crates-io]
wgpu = { version = "0.5", path = "../wgpu-rs" }
wgpu-types = { version = "0.5", path = "../wgpu/wgpu-types" }
wgpu-core = { version = "0.5", path = "../wgpu/wgpu-core" }
wgpu-native = { version = "0.5", path = "../wgpu/wgpu-native" }

#[patch.crates-io]
gfx-hal = { version = "0.5.0", path = "../gfx/src/hal" }
gfx-backend-gl = { version = "0.5.0", path = "/home/zicklag/git/other/gfx/src/backend/gl" }
gfx-backend-empty = { version = "0.5.0", path = "../gfx/src/backend/empty" }
gfx-backend-vulkan = { version = "0.5.0", path = "../gfx/src/backend/vulkan" }
gfx-backend-dx12 = { version = "0.5.0", path = "../gfx/src/backend/dx12" }
gfx-backend-dx11 = { version = "0.5.0", path = "../gfx/src/backend/dx11" }
gfx-descriptor = { version = "0.1.0", path = "../gfx-extras/gfx-descriptor" }
gfx-memory = { version = "0.1.0", path = "../gfx-extras/gfx-memory" }