[package]
name = "simple-invaders"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"

[dependencies]
clipline = "0.2"
pcx = "0.2"
randomize = "3.0"

[dev-dependencies]
byteorder = "1.3"
getrandom = "0.2"
